title: Plates
tagline: Native PHP Templates
description: 'Plates is a Twig inspired, native PHP template system that brings modern template language functionality to native PHP templates.'
google_analytics_tracking_id: UA-46050814-2
menu:
    Getting Started:
        Introduction: '/'
        Simple example: '/simple-example/'
        Installation: '/installation/'
    The Engine:
        Overview: '/engine/'
        File extensions: '/engine/file-extensions/'
        Folders: '/engine/folders/'
    Templates:
        Overview: '/templates/'
        Variables: '/templates/variables/'
        Nesting: '/templates/nesting/'
        Layouts: '/templates/layouts/'
        Sections: '/templates/sections/'
        Inheritance: '/templates/inheritance/'
        Syntax: '/templates/syntax/'
    Extensions:
        Overview: '/extensions/'
        Escape: '/extensions/escape/'
        Batch: '/extensions/batch/'
        URI: '/extensions/uri/'
        Asset: '/extensions/asset/'